In [1]:
number = 15

In [2]:
type(number)

int

In [3]:
dir(number)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes

In [4]:
my_list = [1, 2, 3]

In [5]:
dir(my_list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

## Numpy

In [ ]:
# pip install numpy
# pip3 install numpy

In [6]:
import numpy as np

In [7]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [8]:
array_a = np.array([1, 2, 3, 4])

In [9]:
array_b = np.array([0, .5, 1, 1.5, 2])

In [10]:
array_b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
array_a[0]

1

In [12]:
array_b[-1]

2.0

In [13]:
array_a[:2]

array([1, 2])

In [14]:
array_a.dtype

dtype('int64')

In [15]:
array_b.dtype

dtype('float64')

In [17]:
empty_array = np.array([])

In [19]:
empty_array.dtype

dtype('float64')

In [21]:
np.array([1, 2, 3, 4], dtype=np.float_)

array([1., 2., 3., 4.])

In [22]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [23]:
array_c = np.array(["ada", "lovelace"])

In [24]:
array_c.dtype

dtype('<U8')

### Dimensions and shapes

In [25]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [26]:
array_a.shape

(4,)

In [27]:
my_array.shape

(2, 3)

In [28]:
array_a.ndim

1

In [29]:
my_array.ndim

2

In [30]:
my_array.size

6

In [36]:
my_array = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 6],
        [3, 2, 1]
    ]
])

In [32]:
my_array.ndim

3

In [33]:
my_array.shape

(2, 2, 3)

In [34]:
my_array.size

12

indexing and slicing

In [37]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]    
])

In [38]:
my_array[1]

array([4, 5, 6])

In [39]:
my_array[1][0]

4

In [40]:
my_array[1, 0]

4

In [41]:
my_array[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
my_array[:2, :2]

array([[1, 2],
       [4, 5]])

In [43]:
my_array[1] = np.array([10, 10, 10])

In [44]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [45]:
my_array[2] = 99

In [46]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [47]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [49]:
my_array = np.arange(0,10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
my_array.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [53]:
np.arange(1, 10.1, 4)

array([1., 5., 9.])

In [56]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [57]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [59]:
np.ones((2, 5, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [63]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
my_array = np.random.random((5,2))

In [65]:
my_array

array([[0.13715763, 0.83910414],
       [0.87684969, 0.96525846],
       [0.34952159, 0.22435054],
       [0.4132433 , 0.29261323],
       [0.02430989, 0.67417612]])

In [70]:
np.random.randint(100, size=(5, 5))

array([[20, 88, 17, 83, 73],
       [ 4, 43, 91, 59, 26],
       [94, 42, 64, 38, 26],
       [62, 15, 36, 98, 21],
       [31, 80, 96,  2, 88]])

In [74]:
np.linspace(5, 10, 5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [ ]:
# any(), all(), full(), concatenate()

In [76]:
array1 = np.arange(0, 10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
array1 = array1.reshape(2, 5)

In [78]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [79]:
np.concatenate([array1, array1])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
np.concatenate([array1, array1], axis=1)

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

### statistics

In [86]:
array1 = np.arange(0, 10)
array1 = array1.reshape(2, 5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [87]:
array1.sum()

45

In [88]:
array1.mean()

4.5

In [89]:
array1.std()

2.8722813232690143

In [90]:
array1.var()

8.25

In [91]:
array1.sum(axis=1)

array([10, 35])

In [92]:
array1.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [97]:
array1 + 10

array([[30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [98]:
array1 += 10
array1

array([[30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [100]:
array2 = np.arange(0, 10)
array2 = array2.reshape(5, 2)
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [102]:
array2 + 10
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [103]:
array2 = array2 + 10
array2

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

boolean arrays

In [104]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [105]:
a[0], a[-1]

(0, 3)

In [106]:
a[[0, -1]]

array([0, 3])

In [107]:
a[[True, False, False, True]]

array([0, 3])

In [108]:
a >= 2 

array([False, False,  True,  True])

In [110]:
a[a >= 2]

array([2, 3])

In [111]:
a.mean()

1.5

In [114]:
a[a > a.mean()]

array([2, 3])

In [115]:
a[~(a > a.mean())]

array([0, 1])

In [118]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [119]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

- 100'e kadar rastgele tamsayılardan oluşan, 3,3 bir matris oluşturun.
- 30'dan büyük olanları boolean yöntemi ile filtreleyin.

In [123]:
rand_array = np.random.randint(100, size=(3,3))
rand_array

array([[41, 79, 99],
       [49, 72, 85],
       [23, 20, 58]])

In [126]:
boolean_array = rand_array > 30

In [127]:
boolean_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False,  True]])

In [128]:
rand_array[boolean_array]

array([41, 79, 99, 49, 72, 85, 58])

In [129]:
my_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
array_1 = my_array.reshape(5,2)
array_2 = my_array.reshape(2,5)

In [130]:
array_1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [131]:
array_2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [132]:
np.dot(array_1, array_2)

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

In [133]:
array_2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [134]:
import sys

In [135]:
sys.getsizeof(10)

28

In [137]:
sys.getsizeof(1000**100)

160

In [138]:
np.dtype(int).itemsize

8

In [140]:
np.dtype(np.int8).itemsize

1

In [141]:
np.dtype(float).itemsize

8

In [144]:
sys.getsizeof([1, 2, 3])

88

In [145]:
np.array([1, 2, 3]).nbytes

24

In [146]:
my_list = list(range(100000))

In [147]:
my_array = np.arange(100000)

In [148]:
%time np.sum(my_array ** 2)

CPU times: user 567 µs, sys: 107 µs, total: 674 µs
Wall time: 681 µs


333328333350000

In [149]:
%time sum([number ** 2 for number in my_list])

CPU times: user 29.7 ms, sys: 38 µs, total: 29.7 ms
Wall time: 38.9 ms


333328333350000